metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: prometheus
  period: 10s
  hosts: ["app:8080"]
  metrics_path: /actuator/prometheus
  username: "admin"
  password: "admin"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
